### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jubianchi** [atoum/visibility-extension#13]
We should have a license and it should be the same as the atoum/atoum repository

* [x] a `LICENSE` file
* [x] in the `composer.json` file (`BSD-3-Clause`)
* [x] in the  `README.md` file

**Comment by off99555** [comment]
The first checkbox is done in #19

**Comment by off99555** [comment]
The second checkbox is done in PR #20 .

**Comment by off99555** [comment]
The third checkbox is done in PR #21 .

**Comment by off99555** [comment]
@jubianchi Please come check this issue.
