### ISSUE TITLE
Installation failed with atoum v4

### ISSUE THREAD

**Issue by agaubertAlteca** [atoum/visibility-extension#33]
Hello,
I cant't install this extension with atoum v4. 
```
vendor/bin/atoum -v
atoum version dev-master by Frédéric Hardy (/mnt/c/Projects/DOCKER/xxx/vendor/atoum/atoum)
```
```
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires atoum/visibility-extension ^1.3 -> satisfiable by atoum/visibility-extension[1.3.0].
    - atoum/visibility-extension 1.3.0 requires atoum/atoum ^2.9 | ^3.0 -> found atoum/atoum[2.9.0, 2.9.1, 3.0.0, ..., 3.4.2] but it conflicts with your root composer.json require (^4.0).`
```
The only solution is to downgrade atoum?

Regards

**Comment by Grummfy** [comment]
hello,
yes an update of the plugins must be done.

the change required are
* update namespace
* update composer
* check compatibility to php 7/8

**Comment by agaubertAlteca** [comment]
Ok, thanks.
So as it stands, we can't invoke a private method?
Regards

**Comment by Grummfy** [comment]
well, In fact it was migrate to atoum4 since a wild,but I forget to push the tag .... if you require the v2 of this extension, il will be compatible
