### ISSUE TITLE
create a new tag

### ISSUE THREAD

**Issue by agallou** [atoum/visibility-extension#9]
There is no tag since the https://github.com/atoum/visibility-extension/commit/26874e7d608dec40abbe0c686c4dec8c55648d22 commit, that allows the new method of adding extensions to the runner.

So we can't use it on a .atoum.php file without beeing on dev-master.

Is that ok if I create a 1.0.2 tag for the visibility-extension ?

**Comment by jubianchi** [comment]
https://github.com/atoum/visibility-extension/releases/tag/1.1.0
